name: Build NetShare

on:
  push:
    tags:
      - "v*.*.*"

jobs:  
  build:    
    runs-on: windows-latest
    
    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
#      - name: Setup VSTest
#        uses: darenm/Setup-VSTest@v1

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Echo Workspace
        run: echo $GITHUB_WORKSPACE


      - name: Restore Packages
        run: nuget restore NetShare.sln

      - name: Build Solution
        run: |
          msbuild.exe NetShare.sln /p:platform="Any CPU" /p:configuration="Release"
        
#      - name: Run Tests
#        run: vstest.console.exe .\tests\Sandbox.Tests\bin\Release\Sandbox.Tests.dll

      - name: Navigate to Release dir
        run: cd netshare\bin\release
        
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'netshare.zip'
          path: '${{github.workspace}}\netshare\bin\release'
          exclusions: '*.git* /*node_modules/* .editorconfig'
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: netshare.zip
